inherit_from:
  - https://raw.githubusercontent.com/Aesthetikx/fun_center/master/fun_center.yaml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
